### ISSUE TITLE
In use?

### ISSUE THREAD

**Issue by tamagokun** [mcollina/fridge#1]
Hey @mcollina, I have been working on an API-based CMS platform called "Fridge" (fridgecms.com),  and have some node.js libs for the API client (`fridge_api`). Right now I am working on a platform to easily build apps using the Fridge api through next.js, and was hoping to snag the name `fridge` on npm, but noticed it was being used already. I wondered if this project was in-use or if you'd be willing to let me have the name on npm. No big deal either way, just thought i'd check ^_^

**Comment by mcollina** [comment]
@tamagokun no, it's not a problem. What is your npm username? I would add your ownership there, this turned out not to be a thing.

**Comment by tamagokun** [comment]
that's most excellent. npm username is `tamagokun`

Thank you!

**Comment by mcollina** [comment]
done.

**Comment by tamagokun** [comment]
:tada: amaaaazing. thanks matteo!
